# Generated by Django 5.2 on 2025-05-14 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('spotify_id', models.CharField(max_length=22, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('place', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('spotify_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='BandEntry',
            fields=[
                ('pk', models.CompositePrimaryKey('festival_id', 'band_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.band')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.festival')),
            ],
        ),
        migrations.CreateModel(
            name='UserEntry',
            fields=[
                ('pk', models.CompositePrimaryKey('festival_id', 'user_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('user_status', models.CharField(choices=[('C', 'Considering'), ('G', 'Going')], max_length=1)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.festival')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
