# Generated by Django 5.2.1 on 2025-05-27 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('pk', models.CompositePrimaryKey('band_id', 'user_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('vote', models.CharField(choices=[('1', 'absolutely need to see'), ('2', 'want to see'), ('3', 'could be interesting if works out'), ('4', 'on radar'), ('5', 'not interested')], max_length=1)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.band')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
